"""Actual container reader contract; summaries cannot manufacture executions."""

import hashlib
import json
import subprocess
import sys
from pathlib import Path

import pytest

from sag.agent.receipt_test_rows import _row_parser_program


def parse(tmp_path, files):
    claims = []
    for name, body in files.items():
        path = tmp_path / "target" / "failsafe-reports" / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(body)
        claims.append({"path": str(path), "sha256": hashlib.sha256(body.encode()).hexdigest()})
    manifest = tmp_path / "claims.json"
    manifest.write_text(json.dumps(claims))
    result = subprocess.run(
        [sys.executable, "-c", _row_parser_program(), str(manifest)],
        text=True,
        capture_output=True,
        check=True,
    )
    return json.loads(result.stdout)


JUNIT = '<testsuite tests="1"><testcase classname="a.T" name="one"/></testsuite>'
PROJECTION = "<!-- Generated by org.testng.reporters.JUnitXMLReporter -->" + JUNIT
NATIVE = (
    '<testng-results total="1" passed="1" failed="0" skipped="0"><suite><test>'
    '<class name="a.T"><test-method name="setup" is-config="true" status="PASS"/>'
    '<test-method name="one" status="PASS"/></class></test></suite></testng-results>'
)
SUMMARY = (
    "<failsafe-summary><completed>1</completed><errors>0</errors>"
    "<failures>0</failures><skipped>0</skipped></failsafe-summary>"
)


def test_failsafe_summary_corroborates_but_does_not_add_rows(tmp_path):
    result = parse(tmp_path, {"TEST-a.xml": JUNIT, "failsafe-summary.xml": SUMMARY})
    assert result["status"] == "complete"
    assert result["report_count"] == 2
    assert len(result["rows"]) == 1


def test_testng_config_and_duplicate_junit_projections_are_not_more_executions(tmp_path):
    result = parse(
        tmp_path,
        {
            "testng-results.xml": NATIVE,
            "suite/test.xml": PROJECTION,
            "junitreports/TEST-a.xml": PROJECTION,
        },
    )
    assert result["status"] == "complete"
    assert result["report_count"] == 3
    assert len(result["rows"]) == 1
    assert result["bounds"]["observed_rows"] == result["bounds"]["kept_rows"] == 1


@pytest.mark.parametrize(
    "files, reason",
    [
        (
            {"TEST-a.xml": JUNIT, "failsafe-summary.xml": SUMMARY.replace(">1<", ">3<")},
            "failsafe_summary_count_mismatch",
        ),
        ({"failsafe-summary.xml": SUMMARY}, "failsafe_summary_count_mismatch"),
        ({"testng-results.xml": NATIVE}, "native_testng_identity_unrepresented"),
        (
            {
                "testng-results.xml": NATIVE.replace('passed="1"', 'passed="2"'),
                "TEST-a.xml": PROJECTION,
            },
            "native_testng_count_mismatch",
        ),
        (
            {
                "testng-results.xml": NATIVE,
                "TEST-a.xml": PROJECTION.replace('name="one"', 'name="two"'),
            },
            "native_testng_projection_unverified",
        ),
        ({"unknown.xml": '<results tests="0"/>'}, "unsupported_report_format"),
        (
            {"TEST-a.xml": '<testsuite tests="1"><testcase/><testcase/><testcase/></testsuite>'},
            "declared_testcase_count_mismatch",
        ),
        (
            {
                "TEST-a.xml": '<testsuites tests="1"><testsuite tests="3"><testcase/></testsuite></testsuites>'
            },
            "declared_testcase_count_mismatch",
        ),
        ({"TEST-a.xml": '<testsuite tests="bad"/>'}, "declared_testcase_count_mismatch"),
        ({"TEST-a.xml": "<testsuite>"}, "report_unreadable"),
    ],
)
def test_inconsistent_or_missing_evidence_cannot_become_complete(tmp_path, files, reason):
    result = parse(tmp_path, files)
    assert result["status"] == "unavailable"
    assert reason in result["reasons"]


def test_legitimate_repeated_elements_are_still_distinct_executions(tmp_path):
    repeated = JUNIT.replace('tests="1"', 'tests="2"').replace(
        "</testsuite>", '<testcase classname="a.T" name="one"/></testsuite>'
    )
    result = parse(tmp_path, {"TEST-a.xml": repeated})
    assert result["status"] == "complete"
    assert [row["execution_ordinal"] for row in result["rows"]] == [1, 2]


def test_another_auxiliary_path_cannot_borrow_summary_verification(tmp_path):
    result = parse(
        tmp_path,
        {
            "TEST-a.xml": JUNIT,
            "failsafe-summary.xml": SUMMARY,
            "other.xml": SUMMARY.replace(">1<", ">3<"),
        },
    )
    assert result["status"] == "unavailable"
    assert "auxiliary_report_unverified" in result["reasons"]


def test_duplicate_conflicting_summary_fields_are_not_silently_overwritten(tmp_path):
    body = SUMMARY.replace(
        "<completed>1</completed>", "<completed>3</completed><completed>1</completed>"
    )
    result = parse(tmp_path, {"TEST-a.xml": JUNIT, "failsafe-summary.xml": body})
    assert result["status"] == "unavailable"
    assert "failsafe_summary_invalid" in result["reasons"]


FIXTURES = Path(__file__).parent / "fixtures/d3r1_remediation/report_formats"


def test_archived_struts_testng_projections_contribute_one_execution(tmp_path):
    result = parse(
        tmp_path,
        {
            "testng-results.xml": (FIXTURES / "testng-results.xml").read_text(),
            "Command line suite/test.xml": (FIXTURES / "testng-suite.xml").read_text(),
            "junitreports/TEST-case.xml": (FIXTURES / "testng-junit.xml").read_text(),
        },
    )
    assert result["status"] == "complete"
    assert len(result["rows"]) == 1
    assert result["rows"][0]["name"] == "testRun"


def test_archived_curator_retry_header_preserves_all_three_cases(tmp_path):
    result = parse(tmp_path, {"TEST-case.xml": (FIXTURES / "curator-mismatch.xml").read_text()})
    assert result["status"] == "complete"
    assert result["execution_totals"]["reported"] == 3
    assert len(result["rows"]) == 3
    assert sum(row.get("runner_reruns", 0) for row in result["rows"]) == 1


@pytest.mark.parametrize(
    "corrupt", ["conservation", "observed", "boolean", "status", "count", "unparsed"]
)
def test_host_refuses_inconsistent_fresh_execution_totals(corrupt):
    from test_receipt_assessor import ContainerFS

    from sag.agent.receipt_test_rows import read_delta_testcase_rows

    path = "/workspace/proj/target/surefire-reports/TEST-a.xml"
    container = ContainerFS(files={path: JUNIT})
    original = container._exact_row_read

    def corrupt_read(tokens):
        result = original(tokens)
        payload = json.loads(result["output"])
        totals = payload["execution_totals"]
        if corrupt == "conservation":
            totals["passed"] = 0
        elif corrupt == "observed":
            totals.update(passed=2, reported=2)
        elif corrupt == "boolean":
            totals["reported"] = True
        elif corrupt == "status":
            payload["status"] = "unavailable"
        elif corrupt == "count":
            payload["report_count"] = 0
        else:
            payload["bounds"]["unparsed_reports"] = 1
        result["output"] = json.dumps(payload)
        return result

    container._exact_row_read = corrupt_read
    parsed = read_delta_testcase_rows(
        container.execute_command,
        receipt_id="inv-maven-test-0001",
        delta={"new": [{"path": path, "sha256": hashlib.sha256(JUNIT.encode()).hexdigest()}]},
    )
    assert parsed["status"] == "unavailable"
    assert parsed["reasons"] == ["execution_totals_inconsistent"]
