"""
Standardized Error Codes for Tools

This module defines consistent error codes used across all tools for better
error tracking, automated recovery, and cleaner error handling.
"""

# Parameter/Input Validation Errors
MISSING_PARAMETER = "MISSING_PARAMETER"
INVALID_PARAMETER = "INVALID_PARAMETER"
UNEXPECTED_PARAMETER = "UNEXPECTED_PARAMETER"
EMPTY_INPUT = "EMPTY_INPUT"

# Execution/Runtime Errors
EXECUTION_FAILED = "EXECUTION_FAILED"
OPERATION_FAILED = "OPERATION_FAILED"
COMMAND_BLOCKED = "COMMAND_BLOCKED"
INTERACTIVE_COMMAND = "INTERACTIVE_COMMAND"

# Installation/Setup Errors
INSTALL_FAILED = "INSTALL_FAILED"
UPDATE_FAILED = "UPDATE_FAILED"
CLONE_FAILED = "CLONE_FAILED"
SETUP_FAILED = "SETUP_FAILED"

# Build/Compilation Errors
BUILD_FAILED = "BUILD_FAILED"
TEST_FAILED = "TEST_FAILED"
DEPENDENCY_ERROR = "DEPENDENCY_ERROR"
OUT_OF_MEMORY = "OUT_OF_MEMORY"

# Configuration/Environment Errors
NOT_FOUND = "NOT_FOUND"
VERSION_MISMATCH = "VERSION_MISMATCH"
CONFIG_FAILED = "CONFIG_FAILED"
NO_ORCHESTRATOR = "NO_ORCHESTRATOR"

# Context/State Management Errors
NO_ACTIVE_CONTEXT = "NO_ACTIVE_CONTEXT"
CONTEXT_ERROR = "CONTEXT_ERROR"
TASK_ERROR = "TASK_ERROR"
PREREQUISITE_INCOMPLETE = "PREREQUISITE_INCOMPLETE"

# Network/External Errors
NETWORK_ERROR = "NETWORK_ERROR"
CONNECTION_ERROR = "CONNECTION_ERROR"
PERMISSION_ERROR = "PERMISSION_ERROR"
REPOSITORY_NOT_FOUND = "REPOSITORY_NOT_FOUND"
DIRECTORY_EXISTS = "DIRECTORY_EXISTS"

# Generic/Unexpected Errors
UNKNOWN_TYPE = "UNKNOWN_TYPE"
UNEXPECTED_ERROR = "UNEXPECTED_ERROR"
ANALYSIS_EXCEPTION = "ANALYSIS_EXCEPTION"

# Legacy Mapping (for backward compatibility during transition)
LEGACY_MAPPING = {
    # Parameter errors
    "MISSING_PARAMETERS": MISSING_PARAMETER,
    "MISSING_PATH": MISSING_PARAMETER,
    "MISSING_CONTENT": MISSING_PARAMETER,
    "MISSING_REF_ID": MISSING_PARAMETER,
    "MISSING_PATTERN": MISSING_PARAMETER,
    "MISSING_PACKAGES": MISSING_PARAMETER,
    "MISSING_VERSION": MISSING_PARAMETER,
    "MISSING_REPOSITORY_URL": MISSING_PARAMETER,
    "MISSING_TASK_ID": MISSING_PARAMETER,
    "MISSING_NEW_CONTEXT": MISSING_PARAMETER,
    "MISSING_KEY_RESULTS": MISSING_PARAMETER,
    "MISSING_ENTRY": MISSING_PARAMETER,
    "MISSING_SUMMARY": MISSING_PARAMETER,
    "INVALID_ACTION": INVALID_PARAMETER,
    "INVALID_TASK_ID": INVALID_PARAMETER,
    "INVALID_REGEX": INVALID_PARAMETER,
    "UNEXPECTED_PARAMETERS": UNEXPECTED_PARAMETER,
    "EMPTY_QUERY": EMPTY_INPUT,

    # Execution errors
    "EXECUTION_ERROR": EXECUTION_FAILED,
    "BACKGROUND_EXECUTION_ERROR": EXECUTION_FAILED,
    "MAVEN_EXECUTION_ERROR": EXECUTION_FAILED,
    "GRADLE_EXECUTION_ERROR": EXECUTION_FAILED,
    "SYSTEM_ERROR": EXECUTION_FAILED,
    "READ_FAILED": OPERATION_FAILED,
    "WRITE_FAILED": OPERATION_FAILED,
    "LIST_FAILED": OPERATION_FAILED,
    "SEARCH_ERROR": OPERATION_FAILED,
    "ANALYSIS_FAILED": OPERATION_FAILED,

    # Installation errors
    "MAVEN_INSTALL_FAILED": INSTALL_FAILED,
    "MAVEN_INSTALL_ERROR": INSTALL_FAILED,
    "GRADLE_INSTALLATION_FAILED": INSTALL_FAILED,
    "JAVA_INSTALL_FAILED": INSTALL_FAILED,
    "DEPENDENCY_INSTALLATION_FAILED": INSTALL_FAILED,
    "DEPENDENCY_INSTALLATION_ERROR": INSTALL_FAILED,
    "INSTALL_MISSING_FAILED": INSTALL_FAILED,
    "CLONE_VERIFICATION_FAILED": CLONE_FAILED,
    "CLONE_ERROR": CLONE_FAILED,
    "PROJECT_SETUP_ERROR": SETUP_FAILED,
    "BACKGROUND_START_FAILED": SETUP_FAILED,

    # Build errors
    "MAVEN_BUILD_ERROR": BUILD_FAILED,
    "GRADLE_BUILD_FAILED": BUILD_FAILED,
    "BUILD_VALIDATION_ERROR": BUILD_FAILED,
    "COMPILATION_ERROR": BUILD_FAILED,
    "TEST_FAILURE": TEST_FAILED,

    # Config errors
    "PROJECT_NOT_FOUND": NOT_FOUND,
    "BUILD_FILE_NOT_FOUND": NOT_FOUND,
    "NO_POM_XML": NOT_FOUND,
    "MAVEN_NOT_FOUND": NOT_FOUND,
    "GIT_NOT_INSTALLED": NOT_FOUND,
    "JAVA_NOT_INSTALLED": NOT_FOUND,
    "NO_JAVA_COMPILER": NOT_FOUND,
    "JAVA_BINARIES_NOT_FOUND": NOT_FOUND,
    "TASK_NOT_FOUND": NOT_FOUND,
    "JAVA_VERSION_MISMATCH": VERSION_MISMATCH,
    "JAVA_VERSION_ERROR": VERSION_MISMATCH,
    "JAVA_CONFIG_FAILED": CONFIG_FAILED,
    "POM_PARSE_ERROR": CONFIG_FAILED,

    # Context errors
    "NO_ACTIVE_TASK": NO_ACTIVE_CONTEXT,
    "NO_TRUNK_CONTEXT": NO_ACTIVE_CONTEXT,
    "CONTEXT_INFO_ERROR": CONTEXT_ERROR,
    "CONTEXT_MANAGEMENT_ERROR": CONTEXT_ERROR,
    "ADD_CONTEXT_ERROR": CONTEXT_ERROR,
    "GET_CONTEXT_ERROR": CONTEXT_ERROR,
    "COMPACT_ERROR": CONTEXT_ERROR,
    "LOAD_HISTORY_ERROR": CONTEXT_ERROR,
    "TASK_START_ERROR": TASK_ERROR,
    "COMPLETE_TASK_ERROR": TASK_ERROR,
    "COMPLETE_WITH_RESULTS_ERROR": TASK_ERROR,
    "TASK_NOT_IN_PROGRESS": TASK_ERROR,
    "TASK_COMPLETION_VALIDATION_FAILED": TASK_ERROR,
    "PREREQUISITE_TASKS_INCOMPLETE": PREREQUISITE_INCOMPLETE,
    "REPORT_GENERATION_REQUIRED": PREREQUISITE_INCOMPLETE,

    # Other
    "UNKNOWN_PROJECT_TYPE": UNKNOWN_TYPE,
}