import { ReportDoc } from "sag-workbench"

// NOTE: the shared `reportDoc` fixture uses block types (heading/paragraph/
// list/code) that ReportBlock does NOT recognize — they'd fall through to the
// raw-JSON <pre> fallback. ReportDoc only renders these types: summary,
// evidence, h1, h2, meta, p, status, ul, table. So we build matching blocks
// inline here to exercise the real rendering paths.
const doc = {
  title: "acme-platform — setup report",
  path: "setup-report-20260618-144210.md",
  generated: "2026-06-18 14:42:10",
  blocks: [
    {
      type: "summary",
      heading: "Outcome",
      body: "Build succeeded on all reachable modules. 7 tests fail in acme-cli and acme-web; treat the setup as partial.",
    },
    { type: "status", ok: true, text: "BUILD SUCCESS — mvn -B -T1C verify in 2m 41s" },
    {
      type: "status",
      ok: false,
      text: "7 failing tests across acme-cli, acme-web (maven.test.failure.ignore=true)",
    },
    { type: "h2", text: "Toolchain" },
    { type: "ul", items: ["JDK 17 (Temurin)", "Maven 3.9.6", "JaCoCo 0.8.12"] },
    { type: "h2", text: "Modules" },
    {
      type: "table",
      rows: [
        ["Module", "Build", "Tests", "Line cov"],
        ["acme-core", "success", "540 / 542", "86.4%"],
        ["acme-api", "success", "300 / 300", "81.0%"],
        ["acme-web", "success", "279 / 284", "72.5%"],
        ["acme-cli", "failure", "67 / 85", "64.2%"],
      ],
    },
    { type: "h2", text: "Next steps" },
    {
      type: "p",
      text: "Investigate ArgsTest quoting and RouterTest wildcard matching; rerun the two affected modules with verify.",
    },
    { type: "meta", text: "Generated by sag · session SETUP-acme-20260618-143409" },
  ],
}

export const Document = () => (
  <div style={{ width: 760 }}>
    <ReportDoc doc={doc} />
  </div>
)

export const Empty = () => (
  <div style={{ width: 760 }}>
    <ReportDoc doc={null} />
  </div>
)
